package rules;
import org.folio.ncip.domain.Account;
import org.folio.ncip.domain.Loan;
import org.folio.ncip.domain.Patron;
import org.folio.ncip.domain.ErrorMessage;
import org.folio.ncip.domain.DroolsResponse;




rule "Check All Charges For NCIP"


when
p: Patron(loanCountExceeded() == true)
then
p.canBorrow(false);
end


rule "Check All Fines For NCIP"

when
p: Patron(fineAmountExceeded() == true)
then
p.canBorrow(false);
end



