package rules;
import org.folio.ncip.domain.Account;
import org.folio.ncip.domain.Loan;
import org.folio.ncip.domain.Patron;
import org.folio.ncip.domain.ErrorMessage;
import org.folio.ncip.domain.DroolsResponse;


//IF YOU DO NOT WANT TO USE THESE RULES YOU CAN DELETE
//THEM OR COMMENT THEM OUT

rule "Check All Charges For NCIP"


when
p: Patron(getLoanCount() > 100 )
then
p.canBorrow(false);
end


rule "Check All Fines For NCIP"

when
p: Patron(getAllCharges() > 500)
then
p.canBorrow(false);
end



